models:
    embedding: "path/to/models/LaBSE-en-ru/"
    rut5_sum: "path/to/models/rut5_base_sum/"

data:
  ru_stopwords: "path/to/data/ru_stopwords.txt"
  archive: "path/to/data/news_df_v4.parquet"

params:
  reference_number: 6
  sentence_number: 2
  similarity_threshold: 0.8

connection:
  host: 'HOST_IP'
  port: 'PORT'
  user: 'LOGIN'
  password: 'PASSWORD'
  loglevel: "DEBUG"
  data_path: "path/to/data/news_df_v4.parquet"